export const dashboardCopy = {
  title: "Dashboard подготовки",
  subtitle:
    "Проходите шаги последовательно: данные → бриф → генерация → результат.",
  steps: [
    "Резюме и вакансия",
    "Бриф",
    "Генерация",
    "Результат и прогресс",
  ],
  step1: {
    title: "Шаг 1. Резюме и вакансия",
    resumeLabel: "Текст резюме (опционально)",
    resumePlaceholder:
      "Вставьте резюме, если хотите уточнить персональные рекомендации",
    vacancySourceLabel: "Источник вакансии",
    vacancySourceRaw: "Полный текст вакансии",
    vacancySourceUrl: "Ссылка на вакансию",
    vacancyInputLabel: "Входные данные вакансии",
    vacancyInputUrlPlaceholder: "https://...",
    vacancyInputTextPlaceholder: "Вставьте текст вакансии",
    ingestAction: "Обработать вакансию",
    ingestLoading: "Обрабатываем...",
    processedLabel: "Обработанный текст вакансии",
    processedPlaceholder: "Появится после обработки",
  },
  step2: {
    title: "Шаг 2. Бриф подготовки",
    targetRole: "Целевая роль *",
    targetRolePlaceholder: "Backend Engineer",
    level: "Уровень",
    horizon: "Горизонт подготовки",
    planFormat: "Формат плана",
    weekdayHours: "Часы в будни",
    weekendHours: "Часы в выходные",
    language: "Язык подготовки",
    priorities: "Приоритеты",
    otherPriority: "Другое (опционально)",
    constraints: "Ограничения и предпочтения",
  },
  step3: {
    title: "Шаг 3. Генерация плана",
    subtitle:
      "Минимум для запуска: обработанная вакансия и целевая роль.",
    action: "Сгенерировать план",
    loading: "Генерируем...",
  },
  step4: {
    title: "Шаг 4. Результат плана",
    emptyPlan: "После генерации здесь появится структура плана.",
    planId: "Plan ID:",
    weekPrefix: "Неделя",
    emptyThemes: "Темы не указаны.",
    progressTitle: "Прогресс",
    progressSubtitle:
      "Отмечайте темы прямо в dashboard. Процент и история синхронизируются с backend. Время показано в UTC.",
    completionSuffix: "выполнено",
    loadingProgress: "Загружаем прогресс...",
    progressLoadError: "Не удалось загрузить прогресс.",
    retry: "Повторить",
    emptyTopics: "Пока нет тем прогресса.",
    emptyTopicsHint:
      "Сгенерируйте план, чтобы получить темы и отмечать по ним статус.",
    updatedAtPrefix: "Обновлено:",
    statusLabel: "Статус темы",
    saving: "Сохраняем обновление...",
    historyTitle: "История изменений",
    emptyHistory: "История появится после первого обновления статуса.",
    unchangedDate: "Ещё не обновлялось",
    unavailableDate: "Дата недоступна",
  },
  actions: {
    logout: "Выйти",
    logoutLoading: "Выходим...",
    previous: "Назад",
    next: "Далее",
  },
  messages: {
    loadProgressUnauthorized: "Нужно войти, чтобы увидеть прогресс.",
    sessionExpired: "Сессия истекла. Войдите снова, чтобы продолжить.",
    progressLoadFailed: "Не удалось загрузить прогресс.",
    fillVacancy: "Заполните текст вакансии или ссылку.",
    vacancySuccess: "Текст вакансии успешно обработан.",
    vacancyError: "Ошибка обработки вакансии.",
    generateGuard:
      "Для генерации заполните целевую роль и обработайте вакансию.",
    planSuccess: "План подготовки сгенерирован.",
    planError: "Ошибка генерации плана.",
    progressUpdateError: "Не удалось обновить статус темы.",
    processVacancyFirst: "Сначала обработайте вакансию на шаге 1.",
    targetRoleRequired: "Заполните обязательное поле «Целевая роль».",
    loggedOut: "Вы вышли из системы.",
    logoutError: "Не удалось выйти из системы.",
    authRedirect: "Перейти к входу",
  },
} as const;
